// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3381.Robot;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3381.Robot.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton pickUp;
    public JoystickButton spitOut;
    public JoystickButton hopperSpin;
    public JoystickButton up;
    public JoystickButton hopperSpinBack;
    public JoystickButton rPMBallShooter;
    public JoystickButton ballShooterManual;
    public JoystickButton openButton;
    public JoystickButton closeButton;
    public Joystick joystick;
    public JoystickButton driveSwitch;
    public Joystick joystick2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        joystick2 = new Joystick(1);
        
        driveSwitch = new JoystickButton(joystick2, 1);
        driveSwitch.whileHeld(new CommandDriveReverse());
        joystick = new Joystick(0);
        
        closeButton = new JoystickButton(joystick, 10);
        closeButton.whenPressed(new GearGateClose());
        openButton = new JoystickButton(joystick, 9);
        openButton.whenPressed(new GearGateOpen());
        ballShooterManual = new JoystickButton(joystick, 9);
        ballShooterManual.whileHeld(new CommandBallShooter());
        rPMBallShooter = new JoystickButton(joystick, 11);
        rPMBallShooter.whileHeld(new PIDBallShooter());
        hopperSpinBack = new JoystickButton(joystick, 2);
        hopperSpinBack.whileHeld(new CommandHopperBack());
        up = new JoystickButton(joystick, 5);
        up.whileHeld(new CommandLifterUp());
        hopperSpin = new JoystickButton(joystick, 1);
        hopperSpin.whileHeld(new HopperJam());
        spitOut = new JoystickButton(joystick, 4);
        spitOut.whileHeld(new CommandBallPickUpReverse());
        pickUp = new JoystickButton(joystick, 3);
        pickUp.whileHeld(new CommandBallPickUpForward());


        // SmartDashboard Buttons
        SmartDashboard.putData("AutonomousCommand", new AutonomousCommand());
        SmartDashboard.putData("CommandHopper", new CommandHopper());
        SmartDashboard.putData("HopperJam", new HopperJam());
        SmartDashboard.putData("TimedHopperBack", new TimedHopperBack());
        SmartDashboard.putData("AutoCenterGearOnlyBlue", new AutoCenterGearOnlyBlue());
        SmartDashboard.putData("ResetGyro", new ResetGyro());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        SmartDashboard.putData("AutoStraightGyro", new AutoStraightGyro(75.0));
        
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick() {
        return joystick;
    }

    public Joystick getJoystick2() {
        return joystick2;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

